source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# AcuteKitten Germs
gem 'devise'
gem 'slim-rails'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'acts_as_votable'
gem 'refile', require: 'refile/rails'
gem 'refile-mini_magick'
gem 'better_errors'
gem 'font-awesome-sass'
gem 'masonry-rails'

group :development, :test do
  gem 'byebug'

  gem 'web-console', '~> 2.0'

  gem 'spring'
end

