# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a296b5c224f119917c6c5728fbd7a0e43df03d87757eb1e88fca9e5f772efda84d182ded533c666e1ba3f2887154093dabc9292e4350f9a539dbe987dadf67de

test:
  secret_key_base: ef3db9da8b5a39e386006c2b944a91716efbdfbcc132a314ce18e01811fb88378c53ca5863d3e3ebed5300c69b0601a4a28ab4f303749895c87fa4ee5c655034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
